name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Lucca-07
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          # Defina a branch onde o arquivo será salvo
          git_commit_message: "feat: generate snake contribution"
